// ─────────────────────────────────────────────
//  models/Video.js  —  Mongoose Video schema
//
//  Key design decisions:
//  • status field drives the UI:
//      "uploading" → spinner
//      "processing" → Member 3's FFmpeg worker
//      "ready"     → fully watchable
//      "failed"    → show error state
//  • hlsPath is set by Member 3 after transcoding.
//    Member 4 feeds this into HLS.js.
//  • likedBy / dislikedBy are arrays of user IDs,
//    which lets us enforce "one reaction per user"
//    and compute counts without extra queries.
//  • views is a simple increment counter.
//    Member 2 logs richer analytics separately.
// ─────────────────────────────────────────────
const mongoose = require("mongoose");

const videoSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, "Video title is required"],
      trim: true,
      maxlength: [200, "Title too long"],
    },
    description: {
      type: String,
      default: "",
      maxlength: [5000, "Description too long"],
    },

    // Uploader reference
    uploader: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true, // speeds up "videos by this user" queries
    },

    // ── File paths (set by Multer on upload, updated by Member 3) ──
    rawFilePath: { type: String, default: "" },   // original file on disk
    hlsPath: { type: String, default: "" },       // e.g. uploads/hls/<id>/master.m3u8
    thumbnailPath: { type: String, default: "" }, // auto-generated by Member 3

    // ── Transcoding state machine ──
    status: {
      type: String,
      enum: ["uploading", "processing", "ready", "failed"],
      default: "uploading",
      index: true,
    },

    // ── Engagement ──
    views: { type: Number, default: 0 },
    likedBy: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    dislikedBy: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],

    // ── Metadata ──
    duration: { type: Number, default: 0 }, // seconds, set by Member 3 via FFprobe
    tags: [{ type: String, trim: true }],
    category: { type: String, default: "General" },
    isPublic: { type: Boolean, default: true },

    // ── Comment count — kept in sync by Member 2 ──
    commentCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

// ── Virtuals ─────────────────────────────────
videoSchema.virtual("likeCount").get(function () {
  return this.likedBy.length;
});

videoSchema.virtual("dislikeCount").get(function () {
  return this.dislikedBy.length;
});

// Include virtuals when converting to JSON (so the API response has them)
videoSchema.set("toJSON", { virtuals: true });
videoSchema.set("toObject", { virtuals: true });

// ── Indexes ───────────────────────────────────
videoSchema.index({ title: "text", description: "text", tags: "text" }); // text search
videoSchema.index({ createdAt: -1 });   // newest-first feed
videoSchema.index({ views: -1 });       // trending feed (Member 2)

module.exports = mongoose.model("Video", videoSchema);
